<style>
@font-face {
    font-family: OpenSansLight;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansLight/OpenSansLight.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansRegular;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansRegular/OpenSansRegular.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansSemiBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansSemiBold/OpenSansSemiBold.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansBold/OpenSansBold.woff") format("woff");
    font-weight: normal;
}
.navbar-default {
    background: #ffffff; border: none;
    height: 60px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}
.round-check input[type="checkbox"]:checked + label:before {
    background: #fa8623 !important;
}
.group-messages-wrapper a{
    color: #fa8623 !important;
}
ul.profile-completion-bar li.completion-bar div.completion-bar-status {
    background: #fa8623 !important;
}
.featured-users{
    background: transparent !important;
}
.result-bar {
    background: #fa8623 !important;
}
.featured-users .sidebar-title-back, .featured-users .pro-me-here a {
    color: #050505 !important;
    background: transparent;
    margin-bottom: 10px;
}

.avtive {
    border-color: #fa8623 !important;
}
.loader {
  background-color: transparent !important;
}
.loader:before {
    background-color: #8dd9ff;
}
.left-sidebar ul li a i {
    color: #fa8623 !important;
}
.cs-loader-inner, .main  {
    color: #fa8623;
}
.login input:focus, ul.profile-completion-bar li.completion-bar div.completion-bar-wrapper, .edit_grp_info_modal input.form-control:not(textarea):focus, .verfy_sett_email_phone input.form-control:not(textarea):focus {
    border-color: #fa8623 !important;
}
.login:not(.loading) button:hover {
    background: #1562c6 !important;
    color: #ffffff;
}
.wo_setting_sidebar ul .list-group-item{
    background: #fa8623 !important;
}
.wo_setting_sidebar ul .list-group-item a{
    color: #ffffff;
}
.wo_settings_page .setting-panel input[type=text]:focus, .wo_settings_page .setting-panel input[type=email]:focus, .wo_settings_page .setting-panel input[type=password]:focus, .wo_settings_page .setting-panel select:focus, .wo_settings_page .setting-panel textarea:focus {
    border-color: #03A9F4;
}

#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle{
    border-color: #fa8623;
}
#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle:after{
    background: #fa8623;
}
.login button, .postCategory h5, .wo_search_page .nav-tabs li.active a {
    background: #fa8623 !important;
    color: #ffffff !important;
}
.mejs-controls .mejs-time-rail .mejs-time-current, .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current, .mejs-controls .mejs-volume-button .mejs-volume-slider .mejs-volume-current {
    background-color: #fa8623 !important;
    background: #fa8623 !important;
    background-image: #fa8623 !important;
}
.navbar-default .navbar-nav>.open>a, .navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
}
.navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:focus, .navbar-default .navbar-nav>.active>a:hover, .nav-names li:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
}
body {
    background-color: #f0f2f5;
}
.navbar-default .navbar-nav>li>a {
    color: #050505;
    font-size: 13px;
    margin: 8px 0;
}
a.unread-update {
    color: <?php echo $wo['config']['header_color'];?> !important;
}
.btn-main {
    color: #ffffff;
    background-color: #fa8623;
    border-color: #fa8623;
}
.btn-main:hover {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background-color: #1562c6;
    border-color: #1562c6;
}
.btn-main:focus {
	color: <?php echo $wo['config']['btn_hover_color'];?>;
}
.active-wonder {
    color: #fa8623;
}
.admin-panel .col-md-9 .list-group-item:first-child, .setting-panel .col-md-8 .list-group-item:first-child, .profile-lists .list-group-item:first-child, .col-md-8 .list-group-item:first-child, .col-md-3.custom .list-group-item:first-child, .col-sm-4 .list-group-item:first-child, .col-md-7 .list-group-item:first-child, .col-md-9 .list-group-item:first-child, .red-list .list-group-item:first-child, .active.list-group-item:first-child {
     color: #050505;
     background-color: #fcfcfc;
     border-bottom: 1px solid #f1f1f1;
     padding: 18px;
}
.admin-panel .col-md-9 .list-group-item:first-child a, .setting-panel .col-md-8 .list-group-item:first-child a, .profile-lists .list-group-item:first-child a, .col-md-8 .list-group-item:first-child a, .col-md-7 .list-group-item:first-child a, .active.list-group-item:first-child a {
    color: #050505 !important;
}
.list-group-item.black-list.active-list, .red-list.active-list {
    color: #ffffff;
    background-color: #fa8623;
}
.list-group-item.black-list {
    background: #fa8623;
}
.profile-top-line {
    background-color: #fa8623;
}
#bar {
    background-color: #fa8623;
}
.list-group-item.black-list a{
    color: #ffffff;
}
.list-group-item.black-list.active-list a{
    color: #fa8623;
}
.main-color, .small-text a {
    color: #fa8623 !important;
}
.nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {
    color: #ffffff;
    cursor: default;
    color: #fa8623;
    border-bottom: 1px solid #fa8623;
    background-color: transparent
}
.btn-active {
    color: #ffffff;
    background: #fa8623;
    outline: none;
    border: 1px solid #fa8623
}
.btn-active:hover, .btn-active:focus {
    border: 1px solid #1562c6;
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: #1562c6;
}
.btn-active-color:hover {
    background: #1562c6;
}
.chat-tab .online-toggle-hdr, .wow_thread_head {
    background: #ffffff;
	color: #050505;
}
.chat-tab .online-toggle-hdr a {
	color: #050505;
}
.profile-style .user-follow-button button.btn-active, .btn-login, .btn-register {
    background: #fa8623;
    color: #ffffff;
}
.profile-style .user-follow-button button.btn-active:hover, .btn-login:hover, .btn-login:focus, .btn-register:hover, .btn-register:focus {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: #1562c6;
}
.panel-login>.panel-heading a.active {
    color: #fa8623;
    font-size: 18px;
}
.hash {
    color: #fa8623;
}
.message-text .hash {
    color: #fff !important;
}
.search-container .search-input {
    color: #050505 !important;
    background: #f0f2f5 !important;
}
.chat-messages-wrapper .outgoing .message-text {
    background: <?php echo $wo['config']['chat_outgoing_background'];?>;
}
.normal-container {
    width: 100%;
    height: 100%;
    margin-top: 15px;
}
.active.fa-thumbs-up {
    color: #fa8623;
}
.api-ex-urls {
    background-color: #fa8623; color: #ffffff;
}
.user-username {
    color: #fa8623;
}
.upload-image {
    border: 3px dashed #fa8623;
}
.events-tab-list li { background-color: #fa8623; }
.events-tab-list li:hover { background-color: #fa8623; }
.active-e-tab { background-color: #fa8623 !important; }
.main { color: #fa8623 !important; }
.events-list-dropup-menu ul li a:hover { background: #fa8623; }
.usr-offline { color: #fa8623; }
.blog-dd-ul li span:hover, .blog-dd-ul li a:hover { background: #fa8623 !important; }
.blog_publ {background: #fa8623 ; border: 1px solid #fa8623 ; }
.slide-film-desc:hover, .movies-top-breadcrumb li:hover, .movies-top-breadcrumb li a:hover{
    color: #fa8623 !important;
}
.movies h3.latest-movies, h3.recommended-movies {
    border-left: 3px solid  #fa8623;
}

.wo_user_profile .user-bottom-nav li .menuactive {
    border-bottom: 3px solid #fa8623;
    color:#fa8623;
}
.ads-navbar-wrapper ul li a.active {
	border-color: #fa8623;
}
.ads_mini_wallet, .wo_page_hdng_innr span {
	background-color: #fa8623;
	color: #ffffff;
}
.btn-loading:after {
	background-color: #fa8623;
}
.wow_pub_privacy_menu li label input[type="radio"]:checked+span {
	background-color: #fa8623;color: #ffffff;
}
.order_by ul li.active a {background: #fa8623 !important;color: #ffffff !important;}


<?php 
if ($wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['loggedin'] == true && $wo['page'] != 'messages') { ?>
body, .wo_about_wrapper_parent{padding-left: 21.5%;}
@media (min-width:1140px){
.wow_main_float_head {left: 21.5%;}
}
@media (max-width:1140px){
	.wo_about_wrapper_parent{padding-right: 0px;}
	.wow_main_float_head {right: 0;}
}
<?php } ?>

<?php if($wo['language_type'] == 'rtl' && $wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['page'] != 'messages' && $wo['loggedin'] == true) { ?>
body, .wo_about_wrapper_parent{padding-left: 250px;padding-right: 0px;}
.wow_main_float_head {right: 0;left: 250px;}
@media (max-width:1140px){
	.wo_about_wrapper_parent{padding-left: 0px;}
	.wow_main_float_head {right: 0;left: 0;}
}
<?php } ?>

#welcomeheader .mdbtn:hover{background-color: <?php echo $wo['config']['header_color'];?>;color: <?php echo $wo['config']['header_background'];?>;border-color: <?php echo $wo['config']['header_color'];?>;}

.post .panel.active_shadow {
    box-shadow: 0 0 0 1.5px #fa8623 !important;
}

.ui-widget-header .ui-state-default, .wo_adv_search_filter_side .ui-slider .ui-slider-range, .wo_adv_search_filter_side .ui-slider .ui-slider-handle {
    background-color: #fa8623;
}
<?php
if (!empty($wo['reactions_types'])) {
    foreach ($wo['reactions_types'] as $key => $value) {
?>
.reaction-<?php echo $value['id'];?>::before {
    content: "<?php echo $value['name'];?>";
}
<?php } } ?>
/*.reaction-like::before {
    content: "<?php echo $wo['lang']['like'];?>";
}
.reaction-love::before {
    content: "<?php echo $wo['lang']['love'];?>";
}
.reaction-haha::before {
    content: "<?php echo $wo['lang']['haha'];?>";
}
.reaction-wow::before {
    content: "<?php echo $wo['lang']['wow'];?>";
}
.reaction-sad::before {
    content: "<?php echo $wo['lang']['sad'];?>";
}
.reaction-angry::before {
    content: "<?php echo $wo['lang']['angry'];?>";
}*/

.navbar-default .dropdown-menu.ani-acc-menu >li>a:hover {
    color: #ffffff;background-color: #fa8623;
}
#wo_nw_msg_page .msg_under_hood .mobilerightpane .messages-search-users-form .wo_msg_tabs li.active a, .text-sender-container .msg_usr_info_top_list .msg_usr_cht_opts_btns > span:hover, .text-sender-container .msg_usr_info_top_list .msg_usr_cht_usr_data a:hover, .wo_chat_tabs li.active a {
    color: #fa8623;
}
.text-sender-container .outgoing .message-model .message {background-color: #fa8623;color: #ffffff;}
.text-sender-container .outgoing .message-model .message p, .text-sender-container .outgoing .message-model .message a {color: #ffffff;}

<?php if ($wo['config']['google_map'] == 0) { ?>
#filterby-post li {
    width: 16.5%;
}
<?php }?>
</style>