<?php if ($wo['loggedin'] == true && Wo_IsMobile() == false) { ?>
<div class="left-sidebar">
  <ul>
    <li>
      <a href="<?php echo $wo['user']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username'];?>">
      <img id="updateImage-<?php echo $wo['user']['user_id']?>" src="<?php echo $wo['user']['avatar'];?>" alt="<?php echo $wo['user']['name'];?> Profile Picture"> <?php echo $wo['user']['first_name'];?> <?php echo $wo['user']['last_name'];?>
      </a>
    </li>
    <li>
      <a href="<?php echo Wo_SeoLink('index.php?link1=friends-nearby'); ?>">
      <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/new/friends.png" alt="<?php echo $wo['lang']['friends_btn'];?>">
      </a>
    </li>
    <li>
      <a href="<?php echo Wo_SeoLink('index.php?link1=advertise');?>"  data-ajax="?link1=advertise">
      <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/new/advertisement.png" alt="<?php echo $wo['lang']['advertise'];?>">
      </a>
    </li>
    <?php if ($wo['config']['movies'] == 1) { ?>
    <li>
      <a href="<?php echo Wo_SeoLink('index.php?link1=movies'); ?>">
      <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/new/movies.png" alt="<?php echo $wo['lang']['movies'];?>">
      </a>
    </li>
    <?php } ?>
    <?php if ($wo['config']['funding_system'] == 1) { ?>
    <li>
      <a href="<?php echo Wo_SeoLink('index.php?link1=funding'); ?>" data-ajax="?link1=funding">
        <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/new/fundings.png" alt="<?php echo $wo['lang']['fundings'];?>">
      </a>
    </li>
    <li>
        <a href="<?php echo Wo_SeoLink('index.php?link1=albums'); ?>" data-ajax="?link1=albums">
        <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/new/albums.png" alt="<?php echo $wo['lang']['albums'];?>">
        </a>
      </li>
      <?php if ($wo['config']['common_things'] == 1) { ?>
      <li>
      <li>
        <a href="<?php echo Wo_SeoLink('index.php?link1=common_things'); ?>" data-ajax="?link1=common_things">
        <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/new/common_things.png" alt="<?php echo $wo['lang']['common_things'];?>">
        </a>
      </li>
    <?php } ?>
    <div class="left-menu-more">
      
      <?php } ?>
    </div>
    <!-- <button class="left-menu-btn">
      <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
        <path d="M0 0h24v24H0V0z" fill="none"/>
        <path fill="currentColor" d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"/>
      </svg>
      <?php echo $wo['lang']['see_all']?>
    </button> -->
    <br>
    <hr>
    <li class="link_separator">Explore</li>
    <?php if ($wo['config']['events'] == 1) { ?>
    <li>
      <a href="<?php echo Wo_SeoLink('index.php?link1=events'); ?>" data-ajax="?link1=events">
      <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/event.png" alt="<?php echo $wo['lang']['events'];?>">
      </a>
    </li>
    <?php } ?>
    <?php if ($wo['config']['groups'] == 1) { ?>
    <li>
      <a href="<?php echo Wo_SeoLink('index.php?link1=groups');?>"  data-ajax="?link1=groups">
      <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/group.png" alt="<?php echo $wo['lang']['groups'];?>">
      </a>
    </li>
    <?php } ?>
    <?php if ($wo['config']['pages'] == 1) { ?>
    <li>
      <a href="<?php echo Wo_SeoLink('index.php?link1=pages'); ?>" data-ajax="?link1=pages">
      <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/page.png" alt="<?php echo $wo['lang']['pages'];?>">
      </a>
    </li>
    <?php } ?>
    <?php if ($wo['config']['blogs'] == 1) { ?>
    <li>
      <a href="<?php echo Wo_SeoLink('index.php?link1=my-blogs'); ?>" data-ajax="?link1=my-blogs">
      <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/blog.png" alt="<?php echo $wo['lang']['blogs'];?>">
      </a>
    </li>
    <?php } ?>
    <?php if ($wo['config']['classified'] == 1) { ?>
    <li>
      <a href="<?php echo Wo_SeoLink('index.php?link1=pmy-roducts'); ?>" data-ajax="?link1=my-products">
      <img src="<?php echo $wo['config']['theme_url'];?>/img/left_menu/market.png" alt="<?php echo $wo['lang']['market'];?>">
      </a>
    </li>
    <?php } ?>
  </ul>
  <?php echo Wo_LoadPage('footer/sidebar-footer')?>
</div>
<?php } ?>
<?php if ($wo['config']['order_posts_by'] == 0) { ?>
<script>
  function Wo_StorePosts(type) {
    if (type > 1) {
       return false;
    }
    if (type == 0) {
  	$('.order_all').addClass('active');
  	$('.order_people').removeClass('active');
    } else {
  	$('.order_all').removeClass('active');
  	$('.order_people').addClass('active');
    }
    $('#posts-laoded').html('<div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div><div class="wo_loading_post"><div class="lightui1-shimmer"> <div class="_2iwr"></div> <div class="_2iws"></div> <div class="_2iwt"></div> <div class="_2iwu"></div> <div class="_2iwv"></div> <div class="_2iww"></div> <div class="_2iwx"></div> <div class="_2iwy"></div> <div class="_2iwz"></div> <div class="_2iw-"></div> <div class="_2iw_"></div> <div class="_2ix0"></div> </div></div>');
    $.get(Wo_Ajax_Requests_File() + '?f=update_order_by', {type:type}, function (data) {
      if (data.status == 200) {
        loadposts();
      }
    });
  }
  
  $(document).ready(function(){
    $(".left-menu-btn").click(function(){
      $(".left-menu-more").toggle();
    });
  });


</script>
<?php } ?>