<div class="col-md-4" data-blog-id="<?php echo $wo['article']['id']; ?>">
	<div class="wow_main_blogs">
		<div class="avatar">
			<img src="<?php echo $wo['article']['thumbnail']; ?>" alt="<?php echo $wo['article']['title']; ?>">
			<div class="wow_main_blogs_info">
				<h2 class="art-title"><a href="<?php echo $wo['article']['url']; ?>"><?php echo $wo['article']['title']; ?></a></h2>
				<div class="postMeta--author-text">
					<a href="<?php echo $wo['article']['author']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['article']['author']['username']; ?>"><?php echo $wo['article']['author']['name']; ?></a>
					<span class="middot">·</span>
					<time><?php echo date("d M Y",$wo['article']['posted']); ?></time>
					<span class="middot">·</span>
					<a class="postCategory" href="<?php echo $wo['article']['category_link']; ?>" data-ajax="?link1=blog-category&id=<?php echo $wo['article']['category']; ?>"><?php echo $wo['blog_categories'][$wo['article']['category']]; ?></a>
				</div>
				<a href="<?php echo $wo['article']['url']; ?>" class="btn btn-mat"><i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
			</div>
		</div>
	</div>
</div>