<div class="col-md-4" data-rm-blog="<?php echo $wo['blog']['id']; ?>">
	<div class="wow_main_blogs" id="<?php echo $wo['blog']['id']; ?>">
		<div class="avatar">
			<img src="<?php echo $wo['blog']['thumbnail']; ?>" alt="<?php echo $wo['blog']['title']; ?>">
			<div class="wow_main_blogs_info">
				<h2 class="art-title"><a href="<?php echo $wo['blog']['url']; ?>"><?php echo $wo['blog']['title']; ?></a></h2>
				<div class="postMeta--author-text">
					<a href="<?php echo $wo['blog']['author']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['blog']['author']['username']; ?>"><?php echo $wo['blog']['author']['name']; ?></a>
					<span class="middot">·</span>
					<time><?php echo date("d M Y",$wo['blog']['posted']); ?></time>
					<span class="middot">·</span>
					<a class="postCategory" href="<?php echo $wo['blog']['category_link']; ?>" data-ajax="?link1=blog-category&id=<?php echo $wo['blog']['category']; ?>"><?php echo $wo['blog_categories'][$wo['blog']['category']]; ?></a>
				</div>
				<a href="<?php echo $wo['blog']['url']; ?>" class="btn btn-mat"><i class="fa fa-angle-double-right" aria-hidden="true"></i>
</a>
			</div>
		</div>
	</div>
</div>